---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.5
  - name: windows-2012-r2
    driver:
      http_proxy: null
      https_proxy: null
      box: windows_2012_r2
      customize:
        memory: 2048
    provisioner:
      name: windows_chef_zero
    attributes:
      lsb:
        codename: windows

suites:
  - name: default
    run_list:
      - recipe[sensu::default]
  - name: sysv
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
  - name: runit
    run_list:
      - recipe[sensu-test::runit]
    excludes:
      - windows-2012-r2
  - name: encrypted
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
  - name: vault
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
    attributes:
      dev_mode: true
  - name: asset
    run_list:
      - recipe[sensu-test::asset]
  - name: enterprise
    run_list:
      - recipe[sensu-test::enterprise]
    excludes:
      - windows-2012-r2
