---
driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: centos-5.9
  - name: centos-6.4
  - name: centos-6.5
  - name: windows-2012-r2
    driver:
      http_proxy: null
      https_proxy: null
      box: windows_2012_r2
      customize:
        memory: 2048
    provisioner:
      name: windows_chef_zero
    attributes:
      lsb:
        codename: windows

suites:
  - name: default
    run_list:
      - recipe[sensu::default]
  - name: sysv
    run_list:
      - recipe[sensu-test]
  - name: runit
    run_list:
      - recipe[sensu-test::runit]
  - name: encrypted
    run_list:
      - recipe[sensu-test]
