---
driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.5
  - name: windows-2012-r2
    driver:
      http_proxy: null
      https_proxy: null
      box: windows_2012_r2
      customize:
        memory: 2048
    provisioner:
      name: windows_chef_zero
    attributes:
      lsb:
        codename: windows

suites:
  - name: default
    run_list:
      - recipe[sensu::redis]
      - recipe[sensu::rabbitmq]
      - recipe[sensu::default]
    driver_config:
      network:
        - ['forwarded_port', {guest: 8080, host: 8080}]
  - name: sysv
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
  - name: runit
    run_list:
      - recipe[sensu-test::runit]
    excludes:
      - windows-2012-r2
  - name: encrypted
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
  - name: asset
    run_list:
      - recipe[sensu-test::asset]
