driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: windows-2012-r2
    driver:
      http_proxy: null
      https_proxy: null
      box: windows-2012r2
      customize:
        memory: 2048
    attributes:
      lsb:
        codename: windows

suites:
  - name: default
    run_list:
      - recipe[sensu-test::ensure_group]
      - recipe[sensu::default]
    attributes:
      sensu:
        group: nogroup
        windows:
          dism_source: <%= ENV['SENSU_WINDOWS_DISM_SOURCE'] %>
  - name: sysv
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
      - centos-5.11
      - centos-6.7
  - name: runit
    run_list:
      - recipe[sensu-test::runit]
    excludes:
      - windows-2012-r2
  - name: encrypted
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
  - name: acls
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
      - centos-5.11
    attributes:
      sensu:
        rabbitmq:
          user: sensu_client
  - name: vault
    run_list:
      - recipe[sensu-test]
    excludes:
      - windows-2012-r2
      - centos-5.11
    attributes:
      dev_mode: true
  - name: asset
    run_list:
      - recipe[sensu-test::asset]
  - name: enterprise
    driver:
      customize:
        memory: 3072
    attributes:
      sensu_test:
        enterprise_repo_user: <%= ENV['SENSU_ENTERPRISE_USER'] %>
        enterprise_repo_pass: <%= ENV['SENSU_ENTERPRISE_PASS'] %>
    run_list:
      - recipe[sensu-test::enterprise]
    excludes:
      - windows-2012-r2
  - name: enterprise-dashboard
    attributes:
      sensu_test:
        enterprise_repo_user: <%= ENV['SENSU_ENTERPRISE_USER'] %>
        enterprise_repo_pass: <%= ENV['SENSU_ENTERPRISE_PASS'] %>
    run_list:
      - recipe[sensu-test::enterprise_dashboard]
    excludes:
      - windows-2012-r2
  - name: run-state-helpers
    run_list:
      - recipe[sensu-test::run_state_helpers]
    excludes:
      - windows-2012-r2
