---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[sensu-test]
  sudo: true
- name: runit
  run_list:
    - recipe[sensu-test::runit]
- name: encrypted
  run_list:
    - recipe[sensu-test]
