Encoding:
  Enabled: false

LineLength:
  Max: 200

StringLiterals:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/VariableName:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'test/cookbooks/**/files/**/*'
