Encoding:
  Enabled: false

LineLength:
  Max: 200

StringLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

AllCops:
  Exclude:
    - 'Guardfile'
    - 'tmp/**/*'
    - 'cookbooks/**/*'
    - 'test/cookbooks/**/files/**/*'
