$install_chef = <<SCRIPT
if ! [ -d "/opt/chef" ];
then
    apt-get update
    apt-get install -y curl
    curl -L https://www.opscode.com/chef/install.sh | bash
fi
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.box_url = "https://atlas.hashicorp.com/chef/boxes/ubuntu-14.04/versions/1.0.0/providers/virtualbox.box"

  # config.vm.box = "chef/centos-6.5"
  # config.vm.box_url = "https://atlas.hashicorp.com/chef/boxes/centos-6.5/versions/1.0.0/providers/virtualbox.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "sensu"]
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision :shell, :inline => $install_chef

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.data_bags_path = "data_bags"
    chef.add_recipe "monitor::master"
    chef.add_recipe "monitor::redis"
    chef.add_recipe "monitor::rabbitmq"
  end
end
